### ISSUE TITLE
Unable to Execute CDK Deploy/ CDK bootstrap

### ISSUE THREAD

**Issue by psaimanikanth** [aws-samples/amazon-chime-sdk-pstn-audio-workshop#15]
![image](https://user-images.githubusercontent.com/25593384/177102673-3404c432-79ca-48e9-acc0-ab9f3a4acd6c.png)
F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:42537
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:42537:18)
    at F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\ts-node\src\index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\ts-node\src\index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:116974:26)
    at processTypeReferenceDirectives (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:118456:31)
    at findSourceFileWorker (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:118341:21)
    at findSourceFile (F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:118196:26)
    at F:\Projects\TCS\chime\amazon-chime-sdk-pstn-audio-workshop\node_modules\typescript\lib\typescript.js:118148:85

Subprocess exited with error 1

Attaching Package.json

{
  "name": "amazon-chime-sdk-pstn-audio-workshop",
  "version": "0.1.0",
  "license": "MIT",
  "bin": {
    "amazon-chime-sdk-pstn-audio-workshop": "bin/amazon-chime-sdk-pstn-audio-workshop.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "deploy": "yarn install && yarn build && cdk deploy --outputs-file ./cdk-outputs.json && yarn number",
    "destroy": "cdk destroy",
    "number": "scripts/number",
    "lambda": "scripts/lambda",
    "logs": "scripts/logs",
    "invoke": "scripts/invoke",
    "status": "scripts/status",
    "clean": "scripts/clean",
    "group": "scripts/group",
    "versions": "scripts/versions"
  },
  "devDependencies": {
    "@types/jest": "^26.0.10",
    "@types/node": "10.17.27",
    "aws-cdk": "2.12.0",
    "jest": "^26.4.2",
    "ts-jest": "^26.2.0",
    "ts-node": "^9.1.1",
    "typescript": "^4.6.4"
  },
  "dependencies": {
    "aws-cdk-lib": "2.12.0",
    "cdk-amazon-chime-resources": "^0.0.19",
    "constructs": "^10.0.0",
    "esbuild": "^0.14.23",
    "source-map-support": "^0.5.16",
    "stream": "^0.0.2",
    "typescript": "^4.6.4",
    "uuid": "^8.3.2"
  }
}

**Comment by psaimanikanth** [comment]
Updated all devDependencies to latest version, which solved issue.
